[tool.poetry]
name = "crypto-uncertainty-index"
version = "0.1.0"
description = ""
authors = ["christopher.liew <christopher.liew@bytedance.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
pandas = "^1.3.5"
polars = "^0.12.12"
numpy = "^1.22.1"
nltk = "^3.6.7"
spacy = "^3.2.1"
transformers = "^4.15.0"
scikit-learn = "^1.0.2"
pytorch-lightning = "^1.5.8"
plotly-express = "^0.4.1"
seaborn = "^0.11.2"
tqdm = "^4.62.3"
black = "^21.12b0"
typer-cli = "^0.0.12"
elasticsearch = "^7.16.3"
elasticsearch-dsl = "^7.4.0"
SQLAlchemy = "^1.4.29"
psaw = "^0.1.0"
praw = "^7.5.0"
selenium = "^4.1.0"
bs4 = "^0.0.1"
DateTime = "^4.3"
snscrape = "^0.4.3"
rich = "^11.0.0"
ipykernel = "^6.7.0"
jupyter = "^1.0.0"
sqlmodel = "^0.0.6"
arrow = "^1.2.1"
pmaw = "^2.1.2"
dacite = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"

[tool.poetry.scripts]
crypto-idx = "cli.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
