[tool.poetry]
name = "crypto-uncertainty-index"
version = "0.1.0"
description = ""
authors = ["christopher.liew <christopher.liew@bytedance.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
pandas = "^1.3.5"
numpy = "^1.22.1"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
