title = "Data Extraction & Loading Configuration File"

[elasticsearch]
default_host = "localhost"
default_port = 9200

[elasticsearch.index]
default_num_shards = 5
default_num_replicas = 1

[postgres]
default_local_uri = "postgresql://user:admin@localhost:5432/postgres"

[postgres.tables]
asset_price_table = "asset_prices"
ucry_index_table = "ucry_index"

[reddit.cryptocurrency]
crypto_subreddits = [
    "ethereum",
    "ethtrader",
    "EtherMining",
    "Bitcoin",
    "BitcoinMarkets",
    "btc",
    "CryptoCurrency",
    "CryptoCurrencyTrading",
]
start_date = "2014-01-01"
end_date = "2021-12-31"
save_dir = "crypto_uncertainty_index/etl/raw_data_dump/reddit"

[yfinance]
# TAKEN FROM CRIX MARKET BASKET (7 FEB 2022)
tickers = [
    "BTC-USD",
    "ETH-USD",
    "USDT-USD",
    "XRP-USD",
    "BNB-USD",
    "ADA-USD",
    "DOT-USD",
    "LUNA-USD",
    "GC=F",
    "^GSPC"
]
start_date = "2014-01-01"
end_date = "2021-12-31"
frequency = "1wk"

[kucoin]
base_url = "https://api.kucoin.com"
default_frequency = "1week"
start_date = "2014-01-01"
end_date = "2021-12-31"
save_dir = "crypto_uncertainty_index/etl/raw_data_dump/cryptocurrency" 
